[pytest]
testpaths = tests
addopts = --import-mode=importlib --ignore=tests/realworld
pythonpath = .
norecursedirs = blender_asset_tracer rich .venv reports blendfiles
markers =
    bat: Tests for Blender Asset Tracer
    paths: Tests for path handling and S3 keys
    integration: Integration tests (BAT + Sulu)
    unicode: Tests involving unicode/international characters
    slow: Tests that take a long time to run
    requires_blendfiles: Tests that need .blend files
collect_imported_tests = false
