"""Shared diagnostic issue-code and metadata key constants for submit workflows."""

from __future__ import annotations

# Issue codes
MISSING_DEPENDENCY = "MISSING_DEPENDENCY"
UNREADABLE_DEPENDENCY = "UNREADABLE_DEPENDENCY"
CROSS_DRIVE_EXCLUDED = "CROSS_DRIVE_EXCLUDED"
PROJECT_ABSOLUTE_PATH_REFERENCE = "PROJECT_ABSOLUTE_PATH_REFERENCE"
PROJECT_OUT_OF_ROOT_EXCLUDED = "PROJECT_OUT_OF_ROOT_EXCLUDED"
PROJECT_ROOT_ESCAPE = "PROJECT_ROOT_ESCAPE"
MANIFEST_ENTRY_INVALID = "MANIFEST_ENTRY_INVALID"
MANIFEST_SOURCE_MISMATCH = "MANIFEST_SOURCE_MISMATCH"
UPLOAD_TOUCHED_LT_MANIFEST = "UPLOAD_TOUCHED_LT_MANIFEST"
RCLONE_NO_STATS = "RCLONE_NO_STATS"
RCLONE_EMPTY_TRANSFER = "RCLONE_EMPTY_TRANSFER"
RCLONE_ZERO_TRANSFERS = "RCLONE_ZERO_TRANSFERS"
RCLONE_ERRORS_REPORTED = "RCLONE_ERRORS_REPORTED"

# Metadata keys
META_PROJECT_VALIDATION_VERSION = "project_validation_version"
META_PROJECT_VALIDATION_STATS = "project_validation_stats"
META_MANIFEST_ENTRY_COUNT = "manifest_entry_count"
META_MANIFEST_SOURCE_MATCH_COUNT = "manifest_source_match_count"
META_MANIFEST_VALIDATION_STATS = "manifest_validation_stats"

DEFAULT_PROJECT_VALIDATION_VERSION = "1.0"

ALL_ISSUE_CODES = [
    MISSING_DEPENDENCY,
    UNREADABLE_DEPENDENCY,
    CROSS_DRIVE_EXCLUDED,
    PROJECT_ABSOLUTE_PATH_REFERENCE,
    PROJECT_OUT_OF_ROOT_EXCLUDED,
    PROJECT_ROOT_ESCAPE,
    MANIFEST_ENTRY_INVALID,
    MANIFEST_SOURCE_MISMATCH,
    UPLOAD_TOUCHED_LT_MANIFEST,
    RCLONE_NO_STATS,
    RCLONE_EMPTY_TRANSFER,
    RCLONE_ZERO_TRANSFERS,
    RCLONE_ERRORS_REPORTED,
]

ALL_METADATA_KEYS = [
    META_PROJECT_VALIDATION_VERSION,
    META_PROJECT_VALIDATION_STATS,
    META_MANIFEST_ENTRY_COUNT,
    META_MANIFEST_SOURCE_MATCH_COUNT,
    META_MANIFEST_VALIDATION_STATS,
]
